E-Commerce-Website/E_shop/E_shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from .views import blog_list, blog_detail

from .import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('master/',views.master,name='master'),
    path('',views.index,name='index'),


    path('signup',views.signup,name='signup'),
    path('accounts/' ,include('django.contrib.auth.urls')),
    path('logout/', views.custom_logout, name='logout'),

    #addtocart

    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',
         views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',
         views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/',views.cart_detail,name='cart_detail'),


    #contactpage
    path('contact_us', views.Contact_Page,name="contact_us"),

    #checkoutpage
    path('checkout/', views.CheckOut,name="checkout"),

    #orderpage
    path('order/',views.Your_Order,name="order"),

    #productpage

    path('product/',views.Product_page,name="product"),

    #search
    path('search/',views.Search,name="search"),

    path('blogs/', views.blog_list, name='blogs'),
    path('blogs/<slug:slug>/', views.blog_detail, name='blog_detail'),

    path('product/<str:id>',views.Product_Datil,name="product_detail")

              ]+ static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

E-Commerce-Website/E_shop/app/models.py
from django.db import models

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
import datetime

from django.utils.text import slugify
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name



class Sub_Category(models.Model):
    name = models.CharField(max_length=150)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Brand(models.Model):
    name = models.CharField(max_length=200)


    def __str__(self):
        return self.name


class Product(models.Model):

    Availability = (('In Stock','In Stock'),('Out Of Stock','Out Of Stock'))

    category = models.ForeignKey(Category,on_delete=models.CASCADE,null=False,default='')
    sub_category = models.ForeignKey(Sub_Category, on_delete=models.CASCADE,null=False,default='')
    brand = models.ForeignKey(Brand,on_delete=models.CASCADE,null=True)
    image = models.ImageField(upload_to='ecommerce/pimg')
    name = models.CharField(max_length=100)
    disc = models.CharField(max_length=150)
    price = models.IntegerField()
    discount = models.IntegerField(default=0)
    Availability = models.CharField(choices=Availability,null=True, max_length=100)
    date = models.DateField(auto_now_add=True)

    # Additional Fields
    weight = models.CharField(max_length=50, null=True, blank=True)  # e.g., "1kg", "500g"
    discription = models.TextField(max_length=200, null=True, blank=True)  # Nutritional details
    ingredients = models.TextField(null=True, blank=True)  # Ingredients for edible items

    shelf_life = models.CharField(max_length=100, null=True, blank=True)  # e.g., "6 months"
    packaging_type = models.CharField(max_length=100, null=True, blank=True)  # e.g., "Plastic Bag", "Carton"  # Discount percentage
    rating = models.DecimalField(max_digits=3, decimal_places=2, null=True, blank=True)  # Average customer rating
    reviews_count = models.IntegerField(default=0)  # Total number of reviews
    stock_quantity = models.IntegerField(default=0)  # Quantity available in stock
    sku = models.CharField(max_length=50, unique=True, null=True, blank=True)  # Unique Stock Keeping Unit
    is_featured = models.BooleanField(default=False)  # Highlighted product for promotions
    is_organic = models.BooleanField(default=False)  # Flag for organic products

    # Methods
    def discounted_price(self):
        """Calculate the discounted price."""
        return self.price - (self.price * self.discount // 100)


    def __str__(self):
        return self.name


class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required=True,label='Email',error_messages={'exist': 'This Already Exists'})

    class Meta:
        model = User
        fields = ('username','email','password1','password2')

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['placeholder'] = 'Username'
        self.fields['email'].widget.attrs['placeholder'] = 'E-mail'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

    def clean_email(self):
        if User.objects.filter(email=self.cleaned_data['email']).exists():
            raise forms.ValidationError(self.fields['email'].error_message['exists'])
        return self.cleaned_data['email']



class Contact_us(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    subject = models.CharField(max_length=100)
    message = models.TextField()

    def __str__(self):
        return self.email



class Order(models.Model):
    image = models.ImageField(upload_to='ecommerce/order/image')
    product = models.CharField(max_length=100,default='')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    price = models.IntegerField()
    quantity = models.CharField(max_length=5)
    total = models.CharField(max_length=100, default='')
    address = models.TextField()
    phone = models.CharField(max_length=10)
    pincode = models.CharField(max_length=10)
    date = models.DateField(default=datetime.datetime.today)

    def __str__(self):
        return self.product


class Blog(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(upload_to='blog_images/', null=True, blank=True)
    slug = models.SlugField(unique=True, blank=True)
    published_date = models.DateTimeField(auto_now_add=True)
    is_published = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

E-Commerce-Website/E_shop/templates/blog_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Foody - Organic Food Website Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="/static2/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500&family=Lora:wght@600;700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="/static2/lib/animate/animate.min.css" rel="stylesheet">
    <link href="/static2/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="/static2/csss/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="/static2/csss/style.css" rel="stylesheet">
</head>

<body>

<!-- Spinner Start -->
    <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" role="status"></div>
    </div>
    <!-- Spinner End -->


    <!-- Navbar Start -->
    <div class="container-fluid fixed-top px-0 wow fadeIn" data-wow-delay="0.1s">
        <div class="top-bar row gx-0 align-items-center d-none d-lg-flex">
            <div class="col-lg-6 px-5 text-start">
                <small><i class="fa fa-map-marker-alt me-2"></i>123 Street, New York, USA</small>
                <small class="ms-4"><i class="fa fa-envelope me-2"></i>info@example.com</small>
            </div>
            <div class="col-lg-6 px-5 text-end">
                <small>Follow us:</small>
                <a class="text-body ms-3" href=""><i class="fab fa-facebook-f"></i></a>
                <a class="text-body ms-3" href=""><i class="fab fa-twitter"></i></a>
                <a class="text-body ms-3" href=""><i class="fab fa-linkedin-in"></i></a>
                <a class="text-body ms-3" href=""><i class="fab fa-instagram"></i></a>
            </div>
        </div>

        <nav class="navbar navbar-expand-lg navbar-light py-lg-0 px-lg-5 wow fadeIn" data-wow-delay="0.1s">
            <a href="index.html" class="navbar-brand ms-4 ms-lg-0">
               <img src="/static/images/home/eshoplogo.png" alt="" style="height: 50px; width: auto;" />
            </a>
            <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav ms-auto p-4 p-lg-0">
                    <a href="{% url 'index' %}" class="nav-item nav-link">Home</a>

                </div>

            </div>
        </nav>
    </div>
    <!-- Navbar End -->


    <div class="container-fluid page-header wow fadeIn" data-wow-delay="0.1s">
        <div class="container">
            <h1 class="display-3 mb-3 animated slideInDown">Daily Blogs</h1>
            <nav aria-label="breadcrumb animated slideInDown">
                <ol class="breadcrumb mb-0">
                    <li class="breadcrumb-item"><a class="text-body" href="{% url 'index' %}">Home</a></li>
                </ol>
            </nav>
        </div>
    </div>
    <!-- Page Header End -->


<div class="container">
    <h1>{{ blog.title }}</h1>
    <img class="img-fluid" src="{{ blog.image.url }}" alt="{{ blog.title }}">
    <div class="text-muted mt-4">
        <small class="me-3"><i class="fa fa-user text-primary me-2"></i>{{ blog.author }}</small>
        <small class="me-3"><i class="fa fa-calendar text-primary me-2"></i>{{ blog.published_date|date:"d M, Y" }}</small>
    </div>
    <div class="mt-4">
        <p>{{ blog.content }}</p> <!-- Full content -->
    </div>
</div>



 <!-- Footer Start -->
    <div class="container-fluid bg-dark footer pt-5 wow fadeIn" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-lg-3 col-md-6">
                    <img src="/static/images/home/eshoplogo.png" alt="" style="height: 50px; width: auto;" />
                    <p>Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit, sed stet lorem sit clita</p>
                    <div class="d-flex pt-2">
                        <a class="btn btn-square btn-outline-light rounded-circle me-1" href=""><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-square btn-outline-light rounded-circle me-1" href=""><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-square btn-outline-light rounded-circle me-1" href=""><i class="fab fa-youtube"></i></a>
                        <a class="btn btn-square btn-outline-light rounded-circle me-0" href=""><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-light mb-4">Address</h4>
                    <p><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>
                    <p><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                    <p><i class="fa fa-envelope me-3"></i>info@example.com</p>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-light mb-4">Quick Links</h4>
                    <a class="btn btn-link" href="">About Us</a>
                    <a class="btn btn-link" href="">Contact Us</a>
                    <a class="btn btn-link" href="">Our Services</a>
                    <a class="btn btn-link" href="">Terms & Condition</a>
                    <a class="btn btn-link" href="">Support</a>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-light mb-4">Newsletter</h4>
                    <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                    <div class="position-relative mx-auto" style="max-width: 400px;">
                        <input class="form-control bg-transparent w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                        <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="container-fluid copyright">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                        &copy; <a href="#">Your Site Name</a>, All Right Reserved.
                    </div>
                    <div class="col-md-6 text-center text-md-end">
                        <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                        Designed By <a href="https://htmlcodex.com">HTML Codex</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->

 <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square rounded-circle back-to-top"><i class="bi bi-arrow-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="/static2/lib/wow/wow.min.js"></script>
    <script src="/static2/lib/easing/easing.min.js"></script>
    <script src="/static2/lib/waypoints/waypoints.min.js"></script>
    <script src="/static2/lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Template Javascript -->
    <script src="/static2/jss/main.js"></script>
</body>
</html>

E-Commerce-Website/E_shop/templates/index.html
{% extends 'master.html' %}

{% block head %}
<style>
    #slider-carousel .slider-image {
        width: 100%;
        height: 10px; /* Set the desired height */
        object-fit: cover; /* Ensure the image fills the space without distortion */
    }

    #slider-carousel .col-sm-6 h1 {
        font-size: 2.5rem;
        color: #333;
    }

    #slider-carousel .col-sm-6 h2 {
        font-size: 1.5rem;
        color: #666;
    }

    #slider-carousel .col-sm-6 p {
        font-size: 1rem;
        color: #777;
    }

    #slider-carousel .btn-default.get {
        background-color: #FE980F;
        color: #fff;
        border: none;
        padding: 10px 20px;
        font-size: 1rem;
        border-radius: 20px;
    }

    #slider-carousel .btn-default.get:hover {
        background-color: #e67e22;
        color: #fff;
    }



	<style>
    .feature-box {
        background-color: #ffffff;
        padding: 30px;
        border-radius: 10px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        transition: all 0.3s ease-in-out;
        text-align: center;
    }

    .feature-box:hover {
        box-shadow: 0 8px 15px rgba(0, 0, 0, 0.2);
    }

    .feature-box img {
        max-width: 80px;
        margin-bottom: 20px;
    }

    .feature-box h4 {
        font-size: 1.25rem;
        margin-bottom: 15px;
    }

    .feature-box p {
        font-size: 1rem;
        color: #6c757d;
        margin-bottom: 20px;
    }

    .btn-warning {
        background-color: #ffd700;
        color: #ffffff;
        border: none;
        padding: 10px 20px;
        border-radius: 25px;
        font-size: 1rem;
        transition: background-color 0.3s ease;
    }

    .btn-warning:hover {
        background-color: #e6b800;
    }



</style>

{%endblock%}
{% block body %}
<section id="slider" >
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div id="slider-carousel" class="carousel slide" data-ride="carousel" >
                    <div class="carousel-inner">
                        <!-- First Slide -->
                        <div class="item active">
                            <div class="col-sm-6">
                                <img src="/static/images/home/eshoplogo.png" alt="" style="height: 100px; width: auto;" />
                                <h2>Organic Products</h2>
                                <p>Our grocery e-commerce platform offers a seamless shopping experience, bringing fresh, quality products directly to your doorstep.</p>
                            </div>
                            <div class="col-sm-6">
                                <img src="/static/images/home/c1.png" class="slider-image" alt="First Slide">
                            </div>
                        </div>
                        <!-- Second Slide -->
                        <div class="item">
                            <div class="col-sm-6">
                                <img src="/static/images/home/eshoplogo.png" alt="" style="height: 100px; width: auto;" />
                                <h2>100% Natural Process </h2>
                                <p>With an easy-to-use interface, customers can browse a wide variety of organic and locally-sourced groceries, ensuring healthy choices for every household.</p>
                            </div>
                            <div class="col-sm-6">
                                <img src="/static/images/home/c2.png" class="slider-image" alt="Second Slide">
                            </div>
                        </div>
                        <!-- Third Slide -->
                        <div class="item">
                            <div class="col-sm-6">
                                <img src="/static/images/home/eshoplogo.png" alt="" style="height: 100px; width: auto;" />
                                <h2>Fast Delivery</h2>
                                <p>Our focus on sustainability, fast delivery, and customer satisfaction makes grocery shopping more convenient and eco-friendly than ever before.</p>
                            </div>
                            <div class="col-sm-6">
                                <img src="/static/images/home/c1.png" class="slider-image" alt="Third Slide">
                            </div>
                        </div>
                    </div>

                    <!-- Carousel Controls -->
                    <a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
                        <i class="fa fa-angle-left"></i>
                    </a>
                    <a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
                        <i class="fa fa-angle-right"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>



<!-- Feature Start -->
<div class="container-fluid bg-light" style="background-color: #9acd32; padding: 60px 20px; margin-bottom: 50px; border-radius: 10px; box-shadow: 0px 8px 16px rgba(0, 0, 0, 0.4);">
    <div class="container">
        <div class="section-header text-center mx-auto mb-5">
            <h1 class="display-5 mb-3" style="color: #090909; font-weight: bold; text-shadow: 2px 2px 5px rgba(0,0,0,0.2); margin-top: 0px;">Our Features</h1>
            <p style="font-size: 18px; color: #444; margin-top: 10px;margin-bottom: 20px;">We provide fresh and quality groceries with the convenience of online shopping and timely delivery at your doorstep</p>
        </div>
        <div class="row g-4">
            <div class="col-lg-4 col-md-6">
                <div class="bg-white text-center h-100 p-4 p-xl-5 feature-box"
                     style="box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1); border-radius: 10px; transition: transform 0.3s, box-shadow 0.3s;">
                    <img class="img-fluid mb-4" src="/static/images/home/icon-1.png" alt="Natural Process"
                         style="width: 80px; height: auto;">
                    <h4 class="mb-3" style="color: #555; font-weight: bold;">Natural Process</h4>
                    <p class="mb-4" style="color: #777; font-size: 16px;">We ensure that all our fresh produce is grown and sourced using sustainable and eco-friendly farming methods, free from harmful chemicals.</p>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="bg-white text-center h-100 p-4 p-xl-5 feature-box"
                     style="box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1); border-radius: 10px; transition: transform 0.3s, box-shadow 0.3s;">
                    <img class="img-fluid mb-4" src="/static/images/home/icon-2.png" alt="Organic Products"
                         style="width: 80px; height: auto;">
                    <h4 class="mb-3" style="color: #555; font-weight: bold;">Organic Products</h4>
                    <p class="mb-4" style="color: #777; font-size: 16px;">Our organic products are carefully selected to provide you with the best nature has to offer. Grown without synthetic pesticides or chemicals, that healthier choice for you and your family.</p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Feature End -->








<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2 style="color: #9acd32;">Category</h2>
						<div class="panel-group category-products" id="accordian"><!--category-productsr-->

							{% for cat in category %}
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#{{cat.id}}">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
											{{cat.name}}
										</a>
									</h4>
								</div>
								<div id="{{cat.id}}" class="panel-collapse collapse">
									<div class="panel-body">
										<ul>
											{% for i in cat.sub_category_set.all %}
											<li><a href="/?category={{i.id}}">{{i.name}} </a></li>
											{% endfor %}
										</ul>
									</div>
								</div>
							</div>
							{% endfor %}

						</div><!--/category-products-->

						<div class="brands_products"><!--brands_products-->
							<h2 style="color: #9acd32;">Brands</h2>
							<div class="brands-name">
								<ul class="nav nav-pills nav-stacked">
									{% for i in brand %}
									<li><a href="/?brand={{i.id}}"> <span class="pull-right">(50)</span>{{i.name}}</a></li>
									{% endfor %}
								</ul>
							</div>
						</div><!--/brands_products-->


						<div class="shipping text-center"><!--shipping-->
							<img src="images/home/shipping.jpg" alt="" />
						</div><!--/shipping-->

					</div>
				</div>

				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--features_items-->
						<h2 class="title text-center">
							 <span style="color: #9acd32;">OUR PRODUCT</span>
						</h2>

						{% for prod in product %}
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
										<div class="productinfo text-center">
											<img src="{{prod.image}}" alt="" height="200px;"/>
											<h2>₹{{prod.price}}</h2>
											<p>{{prod.name}}</p>
											<p>{{prod.disc}}</p>
											<a href="{% url 'cart_add' prod.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
										<div class="product-overlay" style="background-color: #9acd32;">
											<div class="overlay-content">
												<h2>₹{{prod.price}}</h2>
												<p>{{prod.name}}</p>
												<p>{{prod.disc}}</p>
												<a href="{% url 'cart_add' prod.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
											</div>
										</div>
								</div>
								
							</div>
						</div>
						</div>
						{% endfor %}

					</div><!--features_items-->

					
				</div>
			</div>
		</div>
	</section>

{% endblock %}

E-Commerce-Website/E_shop/templates/product.html
{% extends 'master.html' %}
{% block body %}

<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Category</h2>
						<div class="panel-group category-products" id="accordian"><!--category-productsr-->

							{% for cat in category %}
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#{{cat.id}}">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
											{{cat.name}}
										</a>
									</h4>
								</div>
								<div id="{{cat.id}}" class="panel-collapse collapse">
									<div class="panel-body">
										<ul>
											{% for i in cat.sub_category_set.all %}
											<li><a href="/product/?category={{i.id}}&brand={{i.id}}">{{i.name}} </a></li>
											{% endfor %}
										</ul>
									</div>
								</div>
							</div>
							{% endfor %}

						</div><!--/category-productsr-->

						<div class="brands_products"><!--brands_products-->
							<h2>Brands</h2>
							<div class="brands-name">
								<ul class="nav nav-pills nav-stacked">
									{% for i in brand %}
									<li><a href="/product/?brand={{i.id}}"> <span class="pull-right"></span>{{i.name}}</a></li>
									{% endfor %}
								</ul>
							</div>
						</div><!--/brands_products-->


						<div class="shipping text-center"><!--shipping-->
							<img src="images/home/shipping.jpg" alt="" />
						</div><!--/shipping-->

					</div>
				</div>

				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--features_items-->
						<h2 class="title text-center">Features Items</h2>

						{% for prod in product %}
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
										<div class="productinfo text-center">
											<img src="/{{prod.image}}" alt="" height="200px;"/>
											<h2>₹{{prod.price}}</h2>
											<p>{{prod.name}}</p>
											<p>{{prod.disc}}</p>
											<a href="{% url 'cart_add' prod.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
										<div class="product-overlay">
											<div class="overlay-content">
												<h2>₹{{prod.price}}</h2>
												<p>{{prod.name}}</p>
												<p>{{prod.disc}}</p>
												<a href="{% url 'cart_add' prod.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
											</div>
										</div>
								</div>
								<div class="choose">
									<ul class="nav nav-pills nav-justified">
										<li><a href="{{prod.id}}"><i class="fa fa-plus-square"></i>View Product</a></li>
									</ul>
								</div>
							</div>
						</div>
						</div>
						{% endfor %}



						<ul class="pagination">
							<li class="active"><a href="">1</a></li>
							<li><a href="">2</a></li>
							<li><a href="">3</a></li>
							<li><a href="">&raquo;</a></li>
						</ul>
					</div><!--features_items-->
				</div>
			</div>
		</div>
	</section>

{% endblock %}